
jQuery(document).ready(function(){$('.collapse').on('shown.bs.collapse',function(){$(this).parent().find(".plus").removeClass("plus").addClass("minus");}).on('hidden.bs.collapse',function(){$(this).parent().find(".minus").removeClass("minus").addClass("plus");});});var onMapMouseleaveHandler=function(event){var that=$(this);that.on('click',onMapClickHandler);that.off('mouseleave',onMapMouseleaveHandler);that.find('iframe').css("pointer-events","none");}
var onMapClickHandler=function(event){var that=$(this);that.off('click',onMapClickHandler);that.find('iframe').css("pointer-events","auto");that.on('mouseleave',onMapMouseleaveHandler);}
jQuery('.maps.embed-container').on('click',onMapClickHandler);jQuery('ul.social a').attr('target','_blank');jQuery('.navbar-header').addClass('wow fadeInLeftBig');jQuery('.top_right').addClass('wow fadeInRightBig');jQuery('.products h2').addClass('wow slideInRight');jQuery('.products .col-md-4.col-sm-4.col-xs-12:nth-of-type(1) .product').addClass('wow slideInLeft');jQuery('.products .col-md-4.col-sm-4.col-xs-12:nth-of-type(2) .product').addClass('wow slideInUp');jQuery('.products .col-md-4.col-sm-4.col-xs-12:nth-of-type(3) .product').addClass('wow slideInRight');jQuery('.proBtn').addClass('wow zoomIn');jQuery('.aboutLeft span').addClass('wow slideInLeft');jQuery('.aboutLeft h3').addClass('wow slideInLeft');jQuery('.aboutLeft a').addClass('wow slideInUp');jQuery('.aboutRight span').addClass('wow slideInRight');jQuery('.aboutRight h3').addClass('wow slideInRight');jQuery('.aboutRight a').addClass('wow slideInUp');jQuery('.instaTitle').addClass('wow zoomIn');jQuery('.footer1 h5').addClass('wow slideInLeft');jQuery('.footer3 h5').addClass('wow slideInRight');jQuery('.footer2 img').addClass('wow zoomIn');jQuery('.subscription').addClass('wow flipInX');jQuery('.footer2 p').addClass('wow flipInX');jQuery('.footer3 ul li').addClass('wow flipInX');jQuery('.subhead').addClass('wow flipInY');jQuery(".wpcf7-form input").click(function(){if(jQuery(this).hasClass("wpcf7-not-valid")){var cName=jQuery(this).parent().prop('className').split(' ')[1];var dClass=".wpcf7-form ."+cName+" span.wpcf7-not-valid-tip";jQuery(dClass).addClass("fadeOutRight");}});jQuery(".wpcf7-form textarea").click(function(){if(jQuery(this).hasClass("wpcf7-not-valid")){var cName=jQuery(this).parent().prop('className').split(' ')[1];var dClass=".wpcf7-form ."+cName+" span.wpcf7-not-valid-tip";jQuery(dClass).addClass("slideOutRight");}});jQuery(function($){if($(window).width()>767){$('.navbar .dropdown').hover(function(){$(this).find('.dropdown-menu').first().stop(true,true).delay(250).slideDown();},function(){$(this).find('.dropdown-menu').first().stop(true,true).delay(200).slideUp();});$('.navbar .dropdown > a').click(function(){location.href=this.href;});}});jQuery(window).load(function(e){wow=new WOW({animateClass:'animated',offset:50});wow.init();});
jQuery("#es_txt_email").keyup(function(e)
{
 jQuery("#error").fadeOut();
});
jQuery('img').attr('width','initial');
jQuery('img').attr('height','initial')
jQuery('.gallery-img-box').addClass('wow zoomIn');
jQuery('.gallery-icon').addClass('wow fadeIn');


